version: '3.8'

services:
  app:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cloude
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Serega9900
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver



  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cloude
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Serega9900
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: