spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/cloude
    username: postgres
    password: Serega9900
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8084

logging:
  level:
    liquibase: DEBUG