spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/cloude
    username: postgres
    password: Serega9900
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:

  session:
    redis:
      flush-mode: on_save


server:
  port: 8084

grpc:
  server:
    port: 9090

logging:
  level:
    com.example: DEBUG
    liquibase: DEBUG
    root: info